### ISSUE TITLE
unattended upgrades apt package installation fails when apt pkgcache is stale

### ISSUE THREAD

**Issue by tim-seoss** [debops/ansible-unattended_upgrades#21]
[debops_unattended_upgrades_apt_stale.txt](https://github.com/debops/ansible-unattended_upgrades/files/1623417/debops_unattended_upgrades_apt_stale.txt)
I was using debops.unattended_upgrades on a slew of dev containers.  It was failing because of stale apt pkgcache contents (some dependencies has been updated, and the old versions were now 404 on the download mirrors).

I made the following patch to selectively update the apt cache.  HTH.

```patch
--- ../ansible-roles/debops.unattended_upgrades/tasks/main.yml.orig     2018-01-11 15:55:43.409834716 +0000
+++ ../ansible-roles/debops.unattended_upgrades/tasks/main.yml  2018-01-11 16:42:53.883543713 +0000
@@ -1,10 +1,18 @@
 ---
 
+- name: Update apt repositories if package cache is more than 1 day old
+  find:
+    paths: /var/cache/apt/
+    patterns: "pkgcache.bin"
+    age: -1d
+  register: aptpkgcache
+
 - name: Install required packages
   apt:
     name: '{{ item }}'
     state: 'present'
     install_recommends: False
+    update_cache: "{{ False if aptpkgcache.files != [] else True }}"
   with_flattened:
     - '{{ unattended_upgrades__base_packages }}'
     - '{{ unattended_upgrades__packages }}'
```

**Comment by tim-seoss** [comment]
[debops_unattended_upgrades_apt_stale.txt](https://github.com/debops/ansible-unattended_upgrades/files/1623418/debops_unattended_upgrades_apt_stale.txt)

**Comment by drybjed** [comment]
The Ansible `apt` module supports the `cache_valid_time` parameter, you could use this instead of checking the age of the database manually in a separate task.

Most DebOps roles don't have these options at the moment, the main playbook checks the cache validity in the beginning and updates it if necessary, otherwise the hosts are supposed to refresh the APT cache by themselves daily. I guess the cache valid time and update cache parameters could be added, especially that there's a centralized mechanism to set the valid time using the `debops.core` role; this probably would help people that use the roles separately. It will probably happen some other time when more pressing matters are resolved. PRs against the DebOps monorepo are of course welcome. :-)

**Comment by tim-seoss** [comment]
Initially, I did look at using cache_valid_time, but it was only introduced in Ansible 2.4 and I thought you might want to support older Ansible versions (find is > 2.0, which is what the meta states as minimum Ansible version for this role).

**Comment by drybjed** [comment]
The `cache_valid_time` was supported from the start [by the `apt` module](https://docs.ansible.com/ansible/latest/apt_module.html), Ansible 2.4 just changed the behaviour of `update_cache` in relation to the former option.

As for the support for different Ansible versions - I try to stick to the current stable Ansible and wait a bit after a release before using newly added features. This for example means that you need Ansible from `stretch-backports` to be usable on Debian Stretch. it's a tradeoff between sticking to current Debian Stable and leveraging new Ansible features, I guess, and it works out well so far.

**Comment by tim-seoss** [comment]
OK, that sounds reasonable, sorry I must have misread the apt module docs.  It would seem reasonable to default to always updating the apt cache when installing the unattended updates package, since (e.g. for use as a standalone role), since the purpose of this module is to automatic explicitly to update the apt cache daily...
